### ISSUE TITLE
unable to install gym-retro/retro

### ISSUE THREAD

**Issue by o9mniej** [Chrispresso/SuperMarioBros-AI#14]
hello i cant install some things to make the ai run what do i do
here is the error:
C:\Users\alex2\Desktop\SuperMarioBros-AI-master>pip install gym-retro
Collecting gym-retro
  Using cached gym-retro-0.7.1.tar.gz (168.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\alex2\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\alex2\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alex2\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 71, in <module>
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\dist.py", line 654, in finalize_options
          ep(self)
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\overlay\Lib\site-packages\setuptools\dist.py", line 674, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\Users\alex2\AppData\Local\Temp\pip-build-env-tquqo5qx\normal\Lib\site-packages\setuptools_scm\_integration\setuptools.py", line 80, in version_keyword
          assert isinstance(value, dict), "version_keyword expects a dict or True"
      AssertionError: version_keyword expects a dict or True
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by requiredtruth** [comment]
i have the exact same issue on linuxmint.

**Comment by axrwl** [comment]
Use [stable-retro](https://github.com/Farama-Foundation/stable-retro) instead.

**Comment by xiaoliang2233** [comment]
<img width="1252" alt="image" src="https://github.com/Chrispresso/SuperMarioBros-AI/assets/17838436/2c440feb-40cd-4dd5-94ec-8664cda557c6">

it takes time to install compatible verison of these deps.

here it is:
gym==0.25.2
gym-retro==0.8.0
importlib-metadata==7.0.1
numpy==1.24.4
pillow==10.2.0
PyQt5==5.15.10

my python version is Python 3.8.18

**Comment by xiaoliang2233** [comment]
your python version is 3.11 I saw. it is only support 3.8. see this doc https://github.com/openai/retro

**Comment by RayKoltner** [comment]
> <img alt="image" width="1252" src="https://private-user-images.githubusercontent.com/17838436/294409948-2c440feb-40cd-4dd5-94ec-8664cda557c6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY1MTE2NTQsIm5iZiI6MTc2NjUxMTM1NCwicGF0aCI6Ii8xNzgzODQzNi8yOTQ0MDk5NDgtMmM0NDBmZWItNDBjZC00ZGQ1LTk0ZWMtODY2NGNkYTU1N2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjIzVDE3MzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1Y2NmMzVlYTEwMjM1ODY5NTEwMzMyYjllM2YwZGRiYjhjMGM0MjYxNTA3ZjQzZDUwYWU4ZWQ3M2Q5N2E5MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hc3m2srp0OFHiTFxAScNsnWU2PrjnLtfLTunbtvC92s">
> it takes time to install compatible verison of these deps.
> 
> here it is: gym==0.25.2 gym-retro==0.8.0 importlib-metadata==7.0.1 numpy==1.24.4 pillow==10.2.0 PyQt5==5.15.10
> 
> my python version is Python 3.8.18

I know it's been a while, but can you tell me if you used venv or some other sort of environment to run this project, and if yes, how did you set it up? I've installed deps you've provided and use python 3.8.9, but retro just refuses to work
