### ISSUE TITLE
can't import World EDIT: & individuals print out error and skip instantly until ... ca. lvl 10 (90 individuals/lvl)

### ISSUE THREAD

**Issue by arch-user-france1** [Chrispresso/SuperMarioBros-AI#6]
france1@ubuntu-desktop:~/Downloads/SuperMarioBros-AI$ python -m retro.import "/home/france1/Dokumente/Super Mario Bros. (World)"
Imported 0 games

france1@ubuntu-desktop:~/Downloads/SuperMarioBros-AI$ python -m retro.import "/home/france1/Dokumente/Super Mario Bros. (World).nes"
Imported 0 games

the file is here: france1@ubuntu-desktop:~/Downloads/SuperMarioBros-AI$ ls /home/france1/Dokumente/Super\ Mario\ Bros.\ \(World\).nes 
'/home/france1/Dokumente/Super Mario Bros. (World).nes'

france1@ubuntu-desktop:~/Downloads/SuperMarioBros-AI$ python -m retro.import '/home/france1/Dokumente/Super Mario Bros. (World).nes'
Imported 0 games

also without these "":
france1@ubuntu-desktop:~/Downloads/SuperMarioBros-AI$ python -m retro.import /home/france1/Dokumente/Super\ Mario\ Bros.\ \(World\).nes 
Imported 0 games

as you see I'm using Linux

**Comment by arch-user-france1** [comment]
here they have also a problem, but on me it isn't saying "**importing 1 potential game**"

https://github.com/openai/retro/issues/36

**Comment by Chrispresso** [comment]
I don't think Linux should make a difference. I've used it in the past for retro and haven't had issues. What version of Python are you using?

**Comment by arch-user-france1** [comment]
france1@ubuntu-desktop:~$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 


I'm using Ubuntu (Linux)
It looks like that the python module doesn't detect that this is a ROM

**Comment by arch-user-france1** [comment]
Steampid is not a game, it thinks the MarioSuperBros.nes is not a game too:


france1@ubuntu-desktop:$ python -m retro.import 
.bash_history              Öffentlich/
.bash_logout               .pki/
.bashrc                    .profile
Bilder/                    .pulse-cookie
.cache/                    .python_history
.config/                   Schreibtisch/
.dbus/                     snap/
Dokumente/                 .ssh/
Downloads/                 .steam/
.dvdcss/                   Steam/
.emacs.d/                  .steampath
.gnupg/                    .steampid
.gphoto/                   .sudo_as_admin_successful
.java/                     .thunderbird/
.local/                    Videos/
.minecraft/                Vorlagen/
.mozilla/                  wartung.sh
Musik/                     wartung.sh
.nv/                       
france1@ubuntu-desktop:$ python -m retro.import .steampid 
Imported 0 games
france1@ubuntu-desktop:$
I removed ~~, cuz else it looks like ~this~ if I don't do that

**Comment by arch-user-france1** [comment]
@Chrispresso  You might can give me your retro file and I try to import this

**Comment by ouhkedu** [comment]
I fix it by >

python -m retro.import .

Importing SuperMarioBros-Nes
Imported 1 games

**Comment by arch-user-france1** [comment]
Now I can't install requirements anymore -_-
More than 2000 (maximum of lines from Terminal) is RED
Here one, I think it can't build wheels anymore but it is working with pycharm!

  make[1]: *** [CMakeFiles/Makefile2:996: CMakeFiles/retro.dir/rule] Fehler 2
  make: *** [Makefile:463: retro] Fehler 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2taa3pig/gym-retro_4482c07eb33245869898acf46194bbf8/setup.py", line 71, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-2taa3pig/gym-retro_4482c07eb33245869898acf46194bbf8/setup.py", line 61, in run
      subprocess.check_call([make_exe, jobs, 'retro'])
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/make', '-j4', 'retro']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for gym-retro
  Running setup.py clean for gym-retro
Successfully built gym
Failed to build pillow gym-retro
Installing collected packages: numpy, scipy, pyglet, pillow, cloudpickle, PyQt5-sip, PyQt5-Qt5, gym, pyqt5, gym-retro
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.1.2
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:


make/cmake not installed?

**Comment by arch-user-france1** [comment]
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
python-pip-whl ist schon die neueste Version (20.3.4-1ubuntu2).
python-pip-whl wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

installed...

**Comment by arch-user-france1** [comment]
warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 864, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 694, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 918, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
  Building wheel for gym-retro (setup.py) ... \^canceled
ERROR: Operation cancelled by user

**Comment by arch-user-france1** [comment]
I can't edit it -_-
                                                ^ 
This is the first error message |

**Comment by arch-user-france1** [comment]
Building wheel for pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cqwgt2om
       cwd: /tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/
  Complete output (170 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 864, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 694, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fwwr4f95/pillow_c655cacd9d6f49fb9b182dc1e7d1e80f/setup.py", line 918, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
  Building wheel for gym-retro (setup.py) ... \^canceled
ERROR: Operation cancelled by user

the whole

**Comment by arch-user-france1** [comment]
fixed by that:

python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow

WHY does the dumb pip install every time a version wich isn't compatible with 3.9???

Installed packages byself:::::: installs old pillow! falllback to python version 3.8::::::::: not in repo

france1@macbook-air:~/Downloads/Python-3.8.3$ sudo bash install-sh 
[sudo] Passwort für france1: 
install-sh: no input file specified.

**Comment by arch-user-france1** [comment]
ran that:

    mkdir debug
    cd debug
    ../configure --with-pydebug
    make
    make test

don't know what it is doing but my laptop cpu is to 90% and Firefox has problems loading. Now it's at 100

**Comment by arch-user-france1** [comment]
configure --enable-optimizations
make
sudo make install
???
Is it possible to have python 3.9 and 3.8 on ubuntu without problems? Pip will not work, right? And all the stuff EDIT: it works (sudo make altinstall)
How can I solve that?

**Comment by arch-user-france1** [comment]
I did it but now
```
france1@macbook-air:~/SuperMarioBros-AI$ pip3.8 install -r requirements.txt 
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting numpy (from -r requirements.txt (line 1))
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/numpy/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/numpy/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/numpy/
^CERROR: Operation cancelled by user
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
france1@macbook-air:~/SuperMarioBros-AI$ 


```

**Comment by arch-user-france1** [comment]
openssl: 
   python3.8: old version
   python3.9: current

how to fix it? I need both!

**Comment by arch-user-france1** [comment]
I installed now Ubuntu 20.10.. So I have python 3.8 shipped
I'll try the fix

**Comment by arch-user-france1** [comment]
thanks soo much it worked

**Comment by arch-user-france1** [comment]
Traceback (most recent call last):
  File "smb_ai.py", line 773, in _update
    self.mario = self.population.individuals[self._current_individual]

??? some just skip, some individuals
